spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:applytrack}
spring.datasource.username=${POSTGRES_USER:applytrack}
spring.datasource.password=${POSTGRES_PASSWORD:applytrack}
