package dev.applytrack.backend.error;

public enum ErrorCode {
    VALIDATION_FAILED,
    MALFORMED_REQUEST,
    RESOURCE_NOT_FOUND,
    ACCESS_DENIED,
    CONFLICT,
    PASSWORD_COMPROMISED,
    INVALID_VERIFICATION_TOKEN,
    VERIFICATION_TOKEN_EXPIRED,
    TOO_MANY_VERIFICATION_REQUESTS,
    INVALID_CREDENTIALS,
    ACCOUNT_TEMPORARILY_LOCKED,
    EMAIL_NOT_VERIFIED,
    INTERNAL_SERVER_ERROR
}
